import Link from "next/link";

export default function Home() {
  return (
    <>
      {/* Dashboard Hero Section */}
      <div className="bg-gradient-to-r from-blue-600 to-blue-700 rounded-2xl p-8 mb-6 text-white">
        <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6">
          {/* Left Side - Welcome Message */}
          <div className="flex-1">
            <h1 className="text-3xl font-bold mb-3 flex items-center gap-2">
              Welcome back, Alexander!
              <span className="text-4xl">👋</span>
            </h1>
            <p className="text-blue-100 text-base mb-6 max-w-xl">
              You have <span className="font-semibold text-white">3 active cases</span> requiring attention and{" "}
              <span className="font-semibold text-white">2 new documents</span> generated by Lindex AI today.
            </p>

            {/* Action Buttons */}
            <div className="flex flex-wrap gap-3">
              <Link
                href="/cases/new"
                className="inline-flex items-center gap-2 px-6 py-3 bg-white text-blue-600 font-semibold rounded-xl hover:bg-blue-50 transition-all transform hover:scale-105 shadow-lg"
              >
                <i className="fa-solid fa-plus"></i>
                New Case
              </Link>
              <Link
                href="#"
                className="inline-flex items-center gap-2 px-6 py-3 bg-white/10 text-white font-semibold rounded-xl hover:bg-white/20 transition-all border-2 border-white/30 backdrop-blur-sm"
              >
                <i className="fa-solid fa-wand-magic-sparkles"></i>
                Ask AI
              </Link>
            </div>
          </div>

          {/* Right Side - Stats Cards */}
          <div className="flex gap-4">
            <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl p-6 min-w-[130px] text-center">
              <div className="text-4xl font-bold mb-1">12</div>
              <div className="text-sm text-blue-100 font-medium">Active Cases</div>
            </div>
            <div className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl p-6 min-w-[130px] text-center">
              <div className="text-4xl font-bold mb-1">48</div>
              <div className="text-sm text-blue-100 font-medium">Documents</div>
            </div>
          </div>
        </div>
      </div>

      {/* Quick Actions */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        <Link
          href="/cases"
          className="bg-white border border-slate-200 rounded-xl p-6 hover:shadow-lg transition-shadow"
        >
          <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
            <i className="fas fa-briefcase text-blue-600 text-xl"></i>
          </div>
          <h3 className="font-semibold text-slate-800 mb-1">New Case</h3>
          <p className="text-sm text-slate-500">Create a new case workspace</p>
        </Link>

        <Link
          href="#"
          className="bg-white border border-slate-200 rounded-xl p-6 hover:shadow-lg transition-shadow"
        >
          <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
            <i className="fas fa-cloud-upload-alt text-green-600 text-xl"></i>
          </div>
          <h3 className="font-semibold text-slate-800 mb-1">Upload Documents</h3>
          <p className="text-sm text-slate-500">Add evidence and files</p>
        </Link>

        <Link
          href="#"
          className="bg-white border border-slate-200 rounded-xl p-6 hover:shadow-lg transition-shadow"
        >
          <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-4">
            <i className="fas fa-robot text-purple-600 text-xl"></i>
          </div>
          <h3 className="font-semibold text-slate-800 mb-1">Ask Lindex AI</h3>
          <p className="text-sm text-slate-500">Get AI-powered insights</p>
        </Link>

        <Link
          href="#"
          className="bg-white border border-slate-200 rounded-xl p-6 hover:shadow-lg transition-shadow"
        >
          <div className="w-12 h-12 bg-orange-100 rounded-lg flex items-center justify-center mb-4">
            <i className="fas fa-calendar-alt text-orange-600 text-xl"></i>
          </div>
          <h3 className="font-semibold text-slate-800 mb-1">Calendar</h3>
          <p className="text-sm text-slate-500">View upcoming events</p>
        </Link>
      </div>

      {/* Recent Cases */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-white border border-slate-200 rounded-xl p-6">
          <h2 className="text-xl font-bold text-slate-800 mb-4">Recent Cases</h2>
          <div className="space-y-3">
            <div className="flex items-start space-x-3 p-3 rounded-lg hover:bg-slate-50 transition-colors">
              <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                <i className="fas fa-briefcase text-blue-600"></i>
              </div>
              <div className="flex-1 min-w-0">
                <h4 className="font-medium text-slate-800 truncate">Johnson v. Smith Corp.</h4>
                <p className="text-sm text-slate-500">Updated 2 hours ago</p>
              </div>
              <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded-full">Active</span>
            </div>
            <div className="flex items-start space-x-3 p-3 rounded-lg hover:bg-slate-50 transition-colors">
              <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                <i className="fas fa-briefcase text-blue-600"></i>
              </div>
              <div className="flex-1 min-w-0">
                <h4 className="font-medium text-slate-800 truncate">Estate of Wilson</h4>
                <p className="text-sm text-slate-500">Updated yesterday</p>
              </div>
              <span className="text-xs bg-yellow-100 text-yellow-700 px-2 py-1 rounded-full">Review</span>
            </div>
            <div className="flex items-start space-x-3 p-3 rounded-lg hover:bg-slate-50 transition-colors">
              <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                <i className="fas fa-briefcase text-blue-600"></i>
              </div>
              <div className="flex-1 min-w-0">
                <h4 className="font-medium text-slate-800 truncate">Martinez Contract Dispute</h4>
                <p className="text-sm text-slate-500">Updated 3 days ago</p>
              </div>
              <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded-full">Active</span>
            </div>
          </div>
          <Link
            href="/cases"
            className="block text-center text-blue-600 hover:text-blue-700 font-medium mt-4 pt-4 border-t border-slate-200"
          >
            View all cases →
          </Link>
        </div>

        {/* Recent Activity */}
        <div className="bg-white border border-slate-200 rounded-xl p-6">
          <h2 className="text-xl font-bold text-slate-800 mb-4">Recent Activity</h2>
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <div className="w-2 h-2 bg-blue-600 rounded-full mt-2"></div>
              <div className="flex-1">
                <p className="text-sm text-slate-800">
                  <span className="font-medium">Document uploaded:</span> Contract_Final.pdf
                </p>
                <p className="text-xs text-slate-500">2 hours ago</p>
              </div>
            </div>
            <div className="flex items-start space-x-3">
              <div className="w-2 h-2 bg-green-600 rounded-full mt-2"></div>
              <div className="flex-1">
                <p className="text-sm text-slate-800">
                  <span className="font-medium">Case updated:</span> Johnson v. Smith Corp.
                </p>
                <p className="text-xs text-slate-500">5 hours ago</p>
              </div>
            </div>
            <div className="flex items-start space-x-3">
              <div className="w-2 h-2 bg-purple-600 rounded-full mt-2"></div>
              <div className="flex-1">
                <p className="text-sm text-slate-800">
                  <span className="font-medium">AI query:</span> Analyzed 15 documents
                </p>
                <p className="text-xs text-slate-500">Yesterday</p>
              </div>
            </div>
            <div className="flex items-start space-x-3">
              <div className="w-2 h-2 bg-orange-600 rounded-full mt-2"></div>
              <div className="flex-1">
                <p className="text-sm text-slate-800">
                  <span className="font-medium">Meeting scheduled:</span> Client consultation
                </p>
                <p className="text-xs text-slate-500">2 days ago</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
